In [1]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [40]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

In [3]:
tokenizer = Tokenizer()

In [6]:
tokenizer.fit_on_texts([faqs])

In [26]:
len(tokenizer.word_index)

312

In [13]:
input_sequences =[]
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [14]:
input_sequences

[[125, 20],
 [125, 20, 38],
 [34, 27],
 [34, 27, 20],
 [34, 27, 20, 37],
 [34, 27, 20, 37, 73],
 [34, 27, 20, 37, 73, 40],
 [34, 27, 20, 37, 73, 40, 74],
 [34, 27, 20, 37, 73, 40, 74, 85],
 [34, 27, 20, 37, 73, 40, 74, 85, 100],
 [34, 27, 20, 37, 73, 40, 74, 85, 100, 38],
 [34, 27, 20, 37, 73, 40, 74, 85, 100, 38, 178],
 [34, 27, 20, 37, 73, 40, 74, 85, 100, 38, 178, 179],
 [20, 37],
 [20, 37, 126],
 [20, 37, 126, 2],
 [20, 37, 126, 2, 75],
 [20, 37, 126, 2, 75, 60],
 [20, 37, 126, 2, 75, 60, 127],
 [20, 37, 126, 2, 75, 60, 127, 61],
 [20, 37, 126, 2, 75, 60, 127, 61, 23],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28, 24],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28, 24, 57],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28, 24, 57, 75],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28, 24, 57, 75, 101],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28, 24, 57, 75, 101, 26],
 [20, 37, 126, 2, 75, 60, 127, 61, 23, 28, 24, 57, 75, 101, 26, 62],
 [20, 37, 126, 2, 75, 60,

In [31]:
max_len =  max([len(x) for x in input_sequences])

57

In [20]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences,maxlen= max_len,padding='pre')

In [21]:
padded_input_sequences

array([[  0,   0,   0, ...,   0, 125,  20],
       [  0,   0,   0, ..., 125,  20,  38],
       [  0,   0,   0, ...,   0,  34,  27],
       ...,
       [  0,   0,   0, ..., 309,  45, 310],
       [  0,   0,   0, ...,  45, 310, 311],
       [  0,   0,   0, ..., 310, 311, 312]], dtype=int32)

In [23]:
x = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [24]:
x

array([[  0,   0,   0, ...,   0,   0, 125],
       [  0,   0,   0, ...,   0, 125,  20],
       [  0,   0,   0, ...,   0,   0,  34],
       ...,
       [  0,   0,   0, ...,   0, 309,  45],
       [  0,   0,   0, ..., 309,  45, 310],
       [  0,   0,   0, ...,  45, 310, 311]], dtype=int32)

In [25]:
y

array([ 20,  38,  27,  20,  37,  73,  40,  74,  85, 100,  38, 178, 179,
        37, 126,   2,  75,  60, 127,  61,  23,  28,  24,  57,  75, 101,
        26,  62, 102,  76,  27,  20, 103, 104,  26,  20,  37, 103, 104,
        26,  20,  37,  27,  35, 105,  63,  20, 103,  37,  73, 180, 102,
        35,  62,  86, 181,  27,  20, 128,  26,  20, 100,  38,  29,  48,
       182,  20, 183, 184, 185, 186,  40,  74,  85, 187,  40,  74,  85,
        40, 190, 106, 191, 130, 131,  31, 194,  20, 195, 128, 108, 109,
       132,  64,  39, 196,  64,  74,  85, 100,  38, 197, 133, 106,  49,
       134,  48,   2, 110,  26,  50,  38, 134,  49, 133, 106, 198,  87,
        77,   2, 110,  26,  50, 199, 200,  51,   5, 136,   2, 137,  65,
        29,   5,  78,   2, 138,  26,  20,  65,  43,  66,  44,  87, 201,
        63, 139,  51,  23, 136,   2,  65,  23,  31, 202, 203,  49,  88,
        20, 138,  31,   5, 204,  20, 140, 205,  50,  89, 207,  24, 111,
        76,  90,  76, 141, 208,  26,  20,  37, 109, 209,  89,  9

In [28]:
from tensorflow.keras.utils import to_categorical
y= to_categorical(y,num_classes=313)

In [27]:
tokenizer.word_index

{'e': 1,
 'a': 2,
 't': 3,
 'o': 4,
 'i': 5,
 's': 6,
 'n': 7,
 'r': 8,
 'h': 9,
 'l': 10,
 'u': 11,
 'c': 12,
 'm': 13,
 'd': 14,
 'p': 15,
 'y': 16,
 'f': 17,
 'w': 18,
 'b': 19,
 'the': 20,
 'g': 21,
 'v': 22,
 'you': 23,
 'to': 24,
 'k': 25,
 'of': 26,
 'is': 27,
 'have': 28,
 'will': 29,
 'j': 30,
 'can': 31,
 '0': 32,
 '1': 33,
 'what': 34,
 '7': 35,
 '2': 36,
 'course': 37,
 'program': 38,
 'in': 39,
 'for': 40,
 '6': 41,
 'x': 42,
 'all': 43,
 'sessions': 44,
 'on': 45,
 '9': 46,
 '5': 47,
 'be': 48,
 'and': 49,
 'this': 50,
 'if': 51,
 'am': 52,
 'pay': 53,
 'payment': 54,
 '3': 55,
 'q': 56,
 'make': 57,
 'we': 58,
 'do': 59,
 'subscription': 60,
 'where': 61,
 'rs': 62,
 'so': 63,
 'campusx': 64,
 'session': 65,
 'our': 66,
 'paid': 67,
 'join': 68,
 'able': 69,
 'your': 70,
 'website': 71,
 'placement': 72,
 'fee': 73,
 'data': 74,
 'monthly': 75,
 'month': 76,
 'not': 77,
 'get': 78,
 'yes': 79,
 'once': 80,
 'past': 81,
 'feb': 82,
 'assistance': 83,
 '’': 84,
 'science':

In [29]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , LSTM , Dense

In [32]:
model = Sequential()
model.add(Embedding(313,100,input_length=56))
model.add(LSTM(150))
model.add(Dense(313,activation='softmax'))

In [36]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 56, 100)           31300     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 313)               47263     
                                                                 
Total params: 229163 (895.17 KB)
Trainable params: 229163 (895.17 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [39]:
model.fit(x,y,epochs=100)

Epoch 1/100
27/27 [==============================] - 3s 101ms/step - loss: 4.0957 - accuracy: 0.2074
Epoch 2/100
27/27 [==============================] - 3s 101ms/step - loss: 3.8466 - accuracy: 0.2445
Epoch 3/100
27/27 [==============================] - 4s 137ms/step - loss: 3.6073 - accuracy: 0.2735
Epoch 4/100
27/27 [==============================] - 3s 124ms/step - loss: 3.3698 - accuracy: 0.3036
Epoch 5/100
27/27 [==============================] - 3s 97ms/step - loss: 3.1536 - accuracy: 0.3372
Epoch 6/100
27/27 [==============================] - 3s 101ms/step - loss: 2.9538 - accuracy: 0.3743
Epoch 7/100
27/27 [==============================] - 3s 115ms/step - loss: 2.7501 - accuracy: 0.4171
Epoch 8/100
27/27 [==============================] - 4s 156ms/step - loss: 2.5736 - accuracy: 0.4415
Epoch 9/100
27/27 [==============================] - 3s 107ms/step - loss: 2.3962 - accuracy: 0.4751
Epoch 10/100
27/27 [==============================] - 3s 97ms/step - loss: 2.2287 - accuracy

In [48]:
import time
text = "what is the fee"
for i in range(10):
  token_text = tokenizer.texts_to_sequences([text])[0]

  padded_token_text = pad_sequences([token_text],maxlen=56,padding='pre')

  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index==pos:
      text = text + " " + word
      time.sleep(1.5)
      print(text)

1/1 [==============================] - 0s 47ms/step
what is the fee of
1/1 [==============================] - 0s 28ms/step
what is the fee of monthly
1/1 [==============================] - 0s 32ms/step
what is the fee of monthly subscription
1/1 [==============================] - 0s 35ms/step
what is the fee of monthly subscription suppose
1/1 [==============================] - 0s 29ms/step
what is the fee of monthly subscription suppose if
1/1 [==============================] - 0s 29ms/step
what is the fee of monthly subscription suppose if i
1/1 [==============================] - 0s 29ms/step
what is the fee of monthly subscription suppose if i pay
1/1 [==============================] - 0s 50ms/step
what is the fee of monthly subscription suppose if i pay on
1/1 [==============================] - 0s 29ms/step
what is the fee of monthly subscription suppose if i pay on 15th
1/1 [==============================] - 0s 35ms/step
what is the fee of monthly subscription suppose if i pay on 

In [42]:
model.predict(padded_token_text)

1/1 [==============================] - 0s 33ms/step


array([[7.47211197e-06, 6.27167856e-06, 2.06080498e-04, 1.02063404e-05,
        2.65644940e-06, 2.37277849e-03, 5.43771057e-06, 4.50104790e-06,
        3.92082165e-06, 2.50126459e-06, 3.85044632e-06, 7.25085783e-06,
        3.72255363e-06, 4.37523568e-06, 1.99484111e-05, 1.05466270e-05,
        9.03317232e-06, 4.39474024e-06, 4.72370266e-06, 3.82998496e-06,
        8.81317351e-03, 9.97300231e-06, 7.53548011e-06, 3.39832250e-03,
        8.30345198e-06, 6.37418680e-06, 1.07259402e-05, 1.72444934e-03,
        6.19430921e-06, 3.14788158e-05, 4.87189709e-06, 3.22680309e-04,
        4.71180192e-06, 7.08487496e-05, 1.38732386e-04, 3.48027897e-05,
        1.24915633e-02, 5.50877849e-05, 8.69122687e-06, 1.35848561e-04,
        2.57161621e-04, 9.60392026e-06, 6.56579004e-06, 2.79887076e-02,
        1.04572850e-04, 7.47793866e-03, 3.23212021e-06, 5.11091685e-06,
        1.98065773e-05, 4.53833770e-03, 3.24828620e-03, 6.01845211e-04,
        9.66159405e-06, 1.17112300e-03, 4.12205583e-04, 4.465190